### GET to local API 
GET http://localhost:3000/users
Content-Type: application/json

###GET for published API 
GET https://cse341-project-yz86.onrender.com/users
Content-Type: application/json

### GET user by ID
GET http://localhost:3000/users/66efb38a229c9cd413a23106
Content-Type: application/json

### Create Contact
POST  http://localhost:3000/users HTTP/1.1
content-Type: application/json

{
    "firstName":"Anne",
    "lastName": "Teixeira",
    "email": "anne@example.com",
    "favoriteColor": "Blue",
    "birthday": "1994-10-15"
}

### PUT contact
PUT http://localhost:3000/users/66efb38a229c9cd413a23106 HTTP/1.1
content-Content-Type: : application/jason

{

"firstName":"Paulo",
    "lastName": "Cauas",
    "email": "paulo@example.com",
    "favoriteColor": "Blue",
    "birthday": "1991-01-04"

}


### DELETE contact
DELETE http://localhost:3000/users/66f609528c921b7fff73d5ce HTTP/1.1

